name: smart_expense_manager
description: Offline-first AI-powered expense manager with on-device SMS parsing.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.1
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  path_provider: ^2.1.6
  flutter_sms_inbox: ^1.0.5
  permission_handler: ^12.0.3
  flutter_animate: ^4.5.2
  fl_chart: ^1.2.0
  google_fonts: ^8.2.0
  lucide_icons: ^0.257.0
  flutter_secure_storage: ^10.3.1
  cryptography: ^2.9.0
  local_auth: ^3.0.2
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  isar_community_generator: ^3.3.2

flutter:
  uses-material-design: true
